version: '3.8'

services:
  similarity-api:
    image: pfmlops.azurecr.io/similarity-api:latest
    ports:
      - 8000:8000

  similarity-ui:
    image: pfmlops.azurecr.io/similarity-ui:latest
    ports:
      - 5000:5000
    depends_on:
      - similarity-api
